info:
  description: Universal-connect-widget data schemas
  title: Universal-Connect-Widget
  version: 1.0.0
openapi: 3.0.0
paths: {}
components:
  schemas:
    Event:
      title: Event object
      description: The schema of the client side events emmitted by the widget.
      type: object
      properties:
        type:
          type: string
        metadata:
          oneOf:
            - $ref: '#/components/schemas/baseData'
            - $ref: '#/components/schemas/ping'
            - $ref: '#/components/schemas/load'
            - $ref: '#/components/schemas/loaded'
            - $ref: '#/components/schemas/institutionSearch'
            - $ref: '#/components/schemas/selectedInstitution'
            - $ref: '#/components/schemas/stepChange'
            - $ref: '#/components/schemas/enterCredentials'
            - $ref: '#/components/schemas/memberStatusUpdate'
            - $ref: '#/components/schemas/submitMFA'
            - $ref: '#/components/schemas/memberConnected'
            - $ref: '#/components/schemas/memberError'

    baseData:
      title: the base event metadata
      description: the base class of the metadatas
      properties:
        user_guid:
          type: string
        session_guid:
          type: string
          
    ping: 
      $ref: '#/components/schemas/baseData'

    load: 
      $ref: '#/components/schemas/baseData'

    loaded:
      title: the loaded event metadata
      allOf:
        - $ref: '#/components/schemas/baseData'
        - type: object
          properties:
            initial_step:
              type: string
    
    institutionSearch:
      title: the institutionSearch event metadata
      allOf:
        - $ref: '#/components/schemas/baseData'
        - type: object
          properties:
            query:
              type: string
  
    selectedInstitution:
      title: the selectedInstitution event metadata
      allOf:
        - $ref: '#/components/schemas/baseData'
        - type: object
          properties:
            guid:
              description: institution_guid
              type: string
            url:
              description: institution_url
              type: string
            name:
              description: institution_name
              type: string

    stepChange:
      title: the stepChange event metadata
      allOf:
        - $ref: '#/components/schemas/baseData'
        - type: object
          properties:
            current:
              type: string
            previous:
              type: string
    
    enterCredentials:
      title: the enterCredentials event metadata
      allOf:
        - $ref: '#/components/schemas/baseData'
        - type: object
          properties:
            institution:
              type: object
              properties:
                guid: 
                  type: string

    memberStatusUpdate:
      title: the memberStatusUpdate event metadata
      allOf:
        - $ref: '#/components/schemas/baseData'
        - type: object
          properties:
            member_guid:
              type: string
            connection_status:
              type: number

    submitMFA:
      title: the submitMFA event metadata
      allOf:
        - $ref: '#/components/schemas/baseData'
        - type: object
          properties: 
            member_guid:
              type: string
    
    memberConnected:
      title: the memberConnected event metadata
      allOf:
        - $ref: '#/components/schemas/baseData'
        - type: object
          properties:
            member_guid:
              type: string
            provider:
              type: string

    memberError:
      title: the enterCredentials event metadata
      allOf:
        - $ref: '#/components/schemas/baseData'
        - type: object
          properties:
            member:
              type: object
              properties:
                guid: 
                  type: string
                connection_status: 
                  type: number